### ISSUE TITLE
python

### ISSUE THREAD

**Issue by LA-hash-hash** [LA-hash-hash/hb_01#2]
装饰器是什么？怎么使用？

**Comment by Pbtsisxins** [comment]
装饰器是一种设计模式，用于在不修改原始函数代码的情况下，增加函数的新功能。装饰器本质上是一个函数，它接受一个函数作为参数并返回一个新的函数，eg:给蛋糕加糖，蛋糕还是那个蛋糕，但变得更好吃了
例子：
def my_decorator(func):
    def wrapper():
        print("开始做蛋糕了！")
        func()  
        print("蛋糕做完了！")
    return wrapper
@my_decorator  #装饰器
def make_cake():
    print("制作蛋糕中...")
调用 make_cake() 时，它会先打印“开始做蛋糕了！”，然后打印“制作蛋糕中...”，最后打印“蛋糕做完了！”。

**Comment by Marshope** [comment]
The decorator is usually applied using the @ syntactic sugar. A basic decorator function looks like this:
def my_decorator(func):
    def wrapper(*args, **kwargs):
        # You can add some code before calling the original function
        print(f"Something is happening before the function {func.__name__} is called.")
        
        # Call the original function and get the result
        result = func(*args, **kwargs)
        
        # You can add some code after calling the original function
        print(f"Something is happening after the function {func.__name__} is called.")
        
        return result
    
    return wrapper

**Comment by loveinabox** [comment]
Python中的装饰器是一种设计模式，用于在不修改类或函数内容的情况下，增加函数或方法的功能。装饰器本质上是一个函数，它接受一个函数作为参数并返回一个新的函数。
装饰器的主要作用是：
1.代码复用：装饰器允许你将代码逻辑从业务逻辑中分离出来，实现代码的复用。
2.增强函数功能：装饰器可以在不修改原有函数代码的情况下，增加额外的功能。

例如：
@decorator_function
def say_hello():
    print("Hello, World!")
这里，say_hello函数被decorator_function装饰器装饰，这意味着在调用say_hello()时，实际上是在调用decorator_function(say_hello)返回的wrapper函数。

**Comment by LA-hash-hash** [comment]
Received, thank you very much.
